### ISSUE TITLE
Release and deploy ITU-MiniTwit.

### ISSUE THREAD

**Issue by ThomasITU** [Devops-2022-Group-R/itu-minitwit#13]
https://github.com/itu-devops/lecture_notes/blob/master/sessions/session_03/README_TASKS.md#b-release-and-deploy-your-itu-minitwit

>   * Prepare a new release with the refactored version of your _ITU-MiniTwit_ latest by **Sunday Feb 20th, at 22:00**) 
>   * Send a pull request to `repositories.py` in our central repository: https://github.com/itu-devops/lecture_notes/blob/master/repositories.py
>     - Add two URLs:
>       * One to your running applications (edit `"http://<minitwit_application_url>"`)
>       * Another one to the simulator API endpoint (edit `"http://<sim_api_url>"`)

**Comment by avborup** [comment]
- api.rhododevdron.swuwu.dk
- rhododevdron.swuwu.dk
