### ISSUE TITLE
Investigate why we are slower than other groups.

### ISSUE THREAD

**Issue by albe2669** [Devops-2022-Group-R/itu-minitwit#60]
- What do we spend time on?
  - Why are we slow with 0 errors?
  - Database? Middleware? Processing? Error handling? Co routines?
- Can we improve?

**Comment by avborup** [comment]
Put latest middleware in goroutine - that might make a small difference

**Comment by avborup** [comment]
And maybe create a database index on username? We might be spending quite a bit of search time with a huge table.
