### ISSUE TITLE
Group O (TBD) tests

### ISSUE THREAD

**Issue by Stribe02** [Devops-2022-Group-R/itu-minitwit#66]
Hello there 😄 
As instructed, we have tested the features suggested:

- Do you see a public timeline? - yes ✅ 
- Does the public timeline show messages that the application received from the simulator? - yes ✅ 
- Can you create a new user? - yes ✅ 
- Can you login as a new user? - yes ✅ 
- Can you write a message? - yes ✅ 
    - it gives responds that the message was recorded -- sees it on timeline after 2 minutes 
    - got an "Error: Network Error" all of the sudden
- After publishing a message, does it appear on you private timeline? ❓ not in our case, unfortunately.
	- 3-4 minutes for loading own timeline with one message (user posted one message) ending in "Error: network Error" and saying "no message so far on the user's own timeline" (haven't inspected with the brower's tool)
- Can you follow another user? ❓ (unknown)
	- Can't check if it is possible to follow a user, as the timeline won't load anymore, (keeps giving Network errors).

- Tried loading public timeline and it gave the same error and "No messages so far"
- public timeline loaded twice, but took awhile after logging in, and asking for public timeline it took over a minute almost two minutes to load

Beside the few errors encountered your site looks great!
If we did perhaps did something wrong, please let us know 😄

**Comment by albe2669** [comment]
Thank you so much for the review. Yeah we are having problems with servers right now, will try to notify you when we are back up :)
